### ISSUE TITLE
NUPlayer 1.2.0 : watching live, always starts at -15 minutes

### ISSUE THREAD

**Issue by davidvde72** [glorang/NUPlayer#3]
When watching live streams, it's not the live stream, but -15 minutes.
I can fast forward to the point where it's "live" again. Looks like it stars from the beginning of the buffer?

NUPlayer 1.2.0 on Mi Box S.

**Comment by glorang** [comment]
Thanks, not sure how I missed that. It got introduced by the fix of #2. 

Fixed in 1.2.1 which is available here and will be available shortly via Google Play Beta Channel.

**Comment by francisduvivier** [comment]
Hi, great project, but if you are planning to put it on the play store, I
would reconsider the name, since there already is an app call NuPlayer on
the play store.

Kind regards,
Francis

**Comment by glorang** [comment]
It's already in Play Store for quite some time now. I was aware there was already an existing NuPlayer but I don't expect too many issues with this, my app is only available in Belgium and theirs is really for some niche market.

Next time open a new issue please instead of replying on an unrelated (and closed) issue.

Thanks,
Geert
