### ISSUE TITLE
Movies section

### ISSUE THREAD

**Issue by davidvde72** [glorang/NUPlayer#4]
Maybe add a "Movies" section next to the "Series"?

**Comment by glorang** [comment]
I've released 1.3.0 in the Beta Channel. It includes support for all Categories, including Movies.

I don't think Movies deserves a separate tab like Series does as there are very little "real" movies.

Let me know what you think about the new release!

**Comment by davidvde72** [comment]
Installed it yesterday, watched a couple of things, no issues.

True about the "Movies". But maybe also remove the "Series" section to be consistent? It's all available under "Categories" now.


THANKS !!!

**Comment by glorang** [comment]
The separate Series section has a few advantages over Series in the Categories section:

- It has a specific sort order (defined by VRT), kind of "popular" / "must-see" / "newest" instead of A-Z sorting
- It excludes certain categories ("nostalgie", duplicates with "audiodescriptie")
- It is able to show the description
- It just looks nice 😄

So I'll keep it as-is for now. I might move it to the Home tab in a later version to be more inline with the real VRT.NU website.

**Comment by davidvde72** [comment]
I prefer A-Z sorting. :-)
Nice work!
