### ISSUE TITLE
App indicated "Please fill in your password" when using mobile phone as remote

### ISSUE THREAD

**Issue by michaelarnauts** [glorang/NUPlayer#5]
Since I have a difficult password, I've used the Android Remote app on my phone to paste my password during setup.

The password was filled in, but the login button complained that "Please fill in your password". When I added a character and removed it, it was fine.

It seems that it wants to have a keypress or something before it allows to continue with login?

**Comment by glorang** [comment]
Yes, you most likely pressed "tab" to switch fields instead of "enter". I agree this is not ideal but this is more a bug in the Leanback library than in NUPlayer.

I'll see if I can improve this or add a notice on the login page maybe.

**Comment by glorang** [comment]
I tried to reproduce this but everything seems to be working for me.

Is it possible you went back to the d-pad in the app after entering your password before pressing "Next" on the keyboard in the remote app ? 

It's the only way I was able to reproduce the issue with the Android Remote app. e.g. full sequence of remote app actions: 

1/ d-pad center to activate e-mail field
2/ enter email via keyboard
3/ select Next on keyboard
4/ enter password via keyboard
5/ switch back to dpad by tapping outside keyboard area
6/ select d-pad down
7/ d-pad center to click login 

That step 5 **must** be a "Next" via the keyboard, it should automatically hide the keyboard and set the focus on the login button.

Let me know if this is what you did or what you did different otherwise please.

For (technical) reference: each input field is an action that will trigger an event once updated so you can get its value but if you press d-pad up/down (or tab on a real keyboard) the event will never be fired and hence the field will be empty even though it is visually filled in. It's how the Leanback team / Google designed it...

**Comment by glorang** [comment]
I've taken the app (or at least all builds) offline on request of VRT so I won't be working on this anymore. Sorry.
